name: zkPass-airdrop-indexer
description: zkPass airdrop indexer
#Global contract definitions that must contain all definitions except
#addresses. Now you can share a single handler/abi/event definitions
#for contracts across multiple chains
contracts:
  - name: Schema
    abi_file_path: ./abis/schema-abi.json
    handler: ./src/SchemaEventHandlers.js
    events:
      - event: SchemaRegistered(bytes32 indexed uid, address registerer, string schemaURI, string schemaData, bool revocable)
      - event: SchemaRevoked(bytes32 indexed uid)
  - name: Zas
    abi_file_path: ./abis/zas-abi.json
    handler: ./src/ZasEventHandlers.js
    events:
      - event: Attested(address indexed recipient, address indexed notary, address allocator, bytes32 uid, bytes32 indexed schema, bytes32 nullifier)
      - event: Revoked(address indexed recipient, address indexed revoker, bytes32 uid, bytes32 indexed schema, bytes32 nullifier)
networks:
  - id: 56 # BSC
    start_block: 37628015
    contracts:
      - name: Schema
        address: "0x4EE7c2e250E6964afC9E1E753D9597b87f531544"
      - name: Zas
        address: "0x876d13a8e0BE8CcA3D6897BaAdb5DcBFBc903aA2"
  - id: 42161 # Arbitrum One
    start_block: 198252017
    contracts:
      - name: Schema
        address: "0xEaCbd088101759f73724dE578AadF36CEcdc3B5e"
      - name: Zas
        address: "0x3b30D7C4e5aa3d7dA11431aF23e8D1F7D25bB0B8"