name: zkPass-airdrop-indexer
description: zkPass airdrop indexer
#Global contract definitions that must contain all definitions except
#addresses. Now you can share a single handler/abi/event definitions
#for contracts across multiple chains
contracts:
  - name: Schema
    abi_file_path: ./abis/schema-abi.json
    handler: ./src/SchemaEventHandlers.js
    events:
      - event: SchemaRegistered(bytes32 indexed uid, address registerer, string schemaURI, string schemaData, bool revocable)
      - event: SchemaDataRevised(bytes32 indexed uid, string schemaData)
      - event: SchemaRevoked(bytes32 indexed uid)
  - name: Zas
    abi_file_path: ./abis/zas-abi.json
    handler: ./src/ZasEventHandlers.js
    events:
      - event: Attested(address indexed recipient, address indexed notary, address allocator, bytes32 uid, bytes32 indexed schema, bytes32 nullifier)
      - event: Revoked(address indexed recipient, address indexed revoker, bytes32 uid, bytes32 indexed schema, bytes32 nullifier)
networks:
  # - id: 1 # ETH
  #   start_block: 0
  #   contracts:
  #     - name: Schema
  #       address: ""
  #     - name: Zas
  #       address: ""
  # - id: 56 # BSC
  #   start_block: 0
  #   contracts:
  #     - name: Schema
  #       address: ""
  #     - name: Zas
  #       address: ""
  # - id: 59144 # Linea
  #   start_block: 0
  #   contracts:
  #     - name: Schema
  #       address: ""
  #     - name: Zas
  #       address: ""
  # - id: 534352 # Scroll
  #   start_block: 0
  #   contracts:
  #     - name: Schema
  #       address: ""
  #     - name: Zas
  #       address: ""
  # - id: 42161 # Arbitrum One
  #   start_block: 0
  #   contracts:
  #     - name: Schema
  #       address: ""
  #     - name: Zas
  #       address: ""
  - id: 324 # zkSync Era
    start_block: 32712932
    contracts:
      - name: Schema
        address: "0x49691a44Dee3A0411C5160E4cfd8f2e52Afb1D5D"
      - name: Zas
        address: "0x7Ed552AbE9e2ba44cDa257D4B510a18480c161D3"
  # - id: 10 # Optimism
  #   start_block: 0
  #   contracts:
  #     - name: Schema
  #       address: ""
  #     - name: Zas
  #       address: ""
  # - id: 137 # Polygon
  #   start_block: 0
  #   contracts:
  #     - name: Schema
  #       address: ""
  #     - name: Zas
  #       address: ""
  # - id: 8453 # Base
  #   start_block: 0
  #   contracts:
  #     - name: Schema
  #       address: ""
  #     - name: Zas
  #       address: ""